package com.omneagate.dpc.Model.EnumModel;

/**
 * Created by user1 on 29/5/15.
 */
public enum TableNames {
    TABLE_DPC_REVENUE_VILLAGE, TABLE_BANK, TABLE_LAND_TYPE, TABLE_DPC_SOCIETY, TABLE_FARMER_CLASS, TABLE_PADDY_CATEGORY, TABLE_DPC_GRADE, TABLE_FARMER_REG_DETAIL, TABLE_FARMER_LAND_DETAIL,
    TABLE_DPC_STATE, TABLE_DPC_DISTRICT, TABLE_DPC_TALUK, TABLE_DPC_VILLAGE,TABLE_DPC_FARMER_REGISTRATION,TABLE_DPC_FARMER_APPROVED_LAND_DETAILS,TABLE_DPC_PADDY_RATE,TABLE_DPC_PROCUREMENT
    ,TABLE_DPC_CAP,TABLE_DPC_TRUCK_MEMO,TABLE_DPC_SPECIFICATION
}

